# Generated by Django 4.2.17 on 2025-02-02 15:52

from django.db import migrations, models
import django.db.models.deletion
import arches_rule_based_permissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("models", "11499_add_editlog_resourceinstance_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleConfig",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("name", models.TextField(default="I need a unique name")),
                ("value", models.JSONField(null=True)),
                (
                    "actions",
                    models.JSONField(
                        default=arches_rule_based_permissions.models.RuleConfig.actions_default
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="groups",
                        related_query_name="group",
                        to="auth.group",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        db_column="nodeid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.node",
                    ),
                ),
                (
                    "nodegroup",
                    models.ForeignKey(
                        db_column="nodegroupid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.nodegroup",
                    ),
                ),
            ],
            options={
                "db_table": "rule_config",
                "managed": True,
            },
        ),
    ]
