# Generated by Django 5.2.7 on 2025-11-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arches_rule_based_permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleconfig',
            name='node',
        ),
        migrations.RemoveField(
            model_name='ruleconfig',
            name='nodegroup',
        ),
    ]
